### ISSUE TITLE
[Feature Request] Filter by: Sender (name only)

### ISSUE THREAD

**Issue by NoNoNo** [aramir/QuickFilterBy#3]
Thank you for your plugin!

I would like to select all messages with the sender name of the selected message, regardless of the e-mail-address.

Example:

* Synoshi Premium \<akruxnz@nirma.jambyl.invalid>
* Synoshi Premium \<aldeypr@fupit.georgia.invalid>
* Synoshi Premium \<ihnupqp@nirma.jambyl.invalid>

Note: Same sender name, but different sender e-mail-address.

In this example, I would like to select all messages with sender name `Synoshi Premium`, regardless of the e-mail-address.

**Comment by aramir** [comment]
Use alt-left-click (on the "From" field) - it does exactly that - filters by the name alone, not by name + email. Alt-clicking on other fields (e..g: subject) - filters by them

Example (I'm just filtering my spam/junk folder here):

![image](https://github.com/aramir/QuickFilterBy/assets/2984000/b89ed850-51d7-4184-984c-b71f09dfc9ec)

Underscored is the one I'll be clicking on. After alt-click/filter applied:

![image](https://github.com/aramir/QuickFilterBy/assets/2984000/5befd2fc-d30d-4926-8261-54477fb6f765)

**Comment by NoNoNo** [comment]
`alt-left-click` works on _Subject_ but not on _Sender_, in my case (TB 115.4 on macOS).

I looked into it, and I found out, that the column name is `correspondentcol-column` instead of the expected name `sender-col`.

https://github.com/aramir/QuickFilterBy/blob/1750dd85176e93833be38ffde3949810f1e91f6d/background.js#L76

```js
      author: (columnName == "sendercol-column" || columnName == "correspondentcol-column")
```

should do the trick.

**Comment by aramir** [comment]
testing https://github.com/aramir/QuickFilterBy/pull/4 on TB `115.4`

**Comment by aramir** [comment]
version 9 submitted to [TB Addons Repo - QuickFilterBy](https://addons.thunderbird.net/en-US/thunderbird/addon/quick-filter-by)

**Comment by aramir** [comment]
@NoNoNo please wait for tb repo to approve/update and enjoy v9 with your suggestion (tested as working on tb 115.4). Thanks!

**Comment by aramir** [comment]
plugin approved & up in TB plugins repo

**Comment by NoNoNo** [comment]
Works like a charm – thank you!
